name: ci

on:
  push:
  pull_request:
    paths:
      - "san/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 16]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: {{ matrix.node }}

      - run: cd san
      - run: npm i
      - run: npm run test
      - run: npm run build

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          name: atomic-class-san-node${{ matrix.node }}
          files: ./coverage/lcov.info
