name: demo ci

on:
  push:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/demo-ci.yml"
      - "demo/**"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: cp -r ./demo ./docs
      - run: sed 's/"\/packages\//"https:\/\/unpkg.com\/@atomic-class\//g' ./docs/dev.html > ./docs/index.0.html
      - run: sed 's/<base href="\/demo\/" \/>//g' ./docs/index.0.html > ./docs/index.html
      - run: rm ./docs/dev.html ./docs/index0.html

      - name: Deploy docs
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs