name: playground ci

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/playground-ci.yml"
      - "playground/**"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: playground

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: npm i -g pnpm
      - run: |
          sed -i "s/\/packages\/playground\//\/atomic-class\/packages\/playground\//" ./src/app.html
          pnpm i
          node build.js
          pnpm check
          pnpm build

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playground/build