name: san ci

on:
  push:
    paths:
      - ".github/workflows/san-ci.yml"
      - "san/**"
  pull_request:
    paths:
      - ".github/workflows/san-ci.yml"
      - "san/**"

jobs:
  build:
    name: san test & build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: san

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: npm i
      - run: npm run test -- --coverage
      - run: npm run build

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          name: atomic-class-san
          files: ./coverage/lcov.info

  publish:
    name: san publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: san
    needs: [build]
    if: github.repository == 'design-to-release/atomic-class'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm i
      - run: npm run rls
      - run: npm publish ./dist --dry-run
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./san/dist/package.json
          access: public
